# Generated by Django 4.2 on 2026-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horainicio', models.TimeField(db_column='horaInicio')),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('metodopago', models.CharField(db_column='metodoPago', max_length=35)),
                ('montototal', models.DecimalField(db_column='montoTotal', decimal_places=2, max_digits=10)),
                ('fechapago', models.DateTimeField(db_column='fechaPago')),
                ('estadopago', models.CharField(db_column='estadoPago', max_length=20)),
                ('codigofactura', models.CharField(db_column='codigoFactura', max_length=20)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('nombreservicio', models.CharField(db_column='nombreServicio', max_length=60)),
                ('duracion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiposervicio', models.CharField(db_column='tipoServicio', max_length=60)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
    ]
