# Generated by Django 4.2.19 on 2026-07-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.AutoField(db_column='idAgenda', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('idbarbero', models.AutoField(db_column='idBarbero', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'barbero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
