# Generated by Django 4.2.19 on 2026-07-02 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('nombreservicio', models.CharField(db_column='nombreServicio', max_length=45)),
                ('precioservicio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10, max_length=10)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('barbero', 'Barbero'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idnotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='info', max_length=30)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idusuariofk', models.ForeignKey(db_column='idUsuarioFk', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fechacreacion'],
            },
        ),
    ]
