# Generated by Django 4.2 on 2026-07-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cita_cliente_servicio_perfilusuario_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idcalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idcitafk', models.OneToOneField(db_column='idCitaFk', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='usuarios.cita')),
                ('idclientefk', models.ForeignKey(db_column='idClienteFk', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.cliente')),
            ],
            options={
                'db_table': 'calificacion',
                'ordering': ['-fechacreacion'],
            },
        ),
    ]
