# Generated by Django 4.2.30 on 2026-08-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password_provisional',
            field=models.BooleanField(default=False),
        ),
    ]