# Generated by Django 4.2.30 on 2026-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_pago_barberodestacado_contenidoindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('metodopago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('PSE', 'PSE'), ('Tarjeta', 'Tarjeta de Crédito/Débito')], db_column='metodoPago', default='Efectivo', max_length=35)),
                ('montototal', models.DecimalField(blank=True, db_column='montoTotal', decimal_places=2, max_digits=10, null=True)),
                ('fechapago', models.DateTimeField(blank=True, db_column='fechaPago', null=True)),
                ('estadopago', models.CharField(blank=True, choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], db_column='estadoPago', default='PENDIENTE', max_length=15, null=True)),
                ('codigofactura', models.CharField(blank=True, db_column='codigoFactura', max_length=20, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BarberoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(help_text='Ej: Cortes Clásicos · Afeitado', max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='index/barberos/')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Barbero destacado (portada)',
                'verbose_name_plural': 'Barberos destacados (portada)',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_etiqueta', models.CharField(default='Barbería moderna', max_length=60)),
                ('hero_titulo', models.CharField(default='Estilo, precisión y confianza en cada corte', max_length=150)),
                ('hero_descripcion', models.TextField(default='En M&A Barber Shop combinamos tradición, elegancia e innovación para ofrecer una experiencia de barbería organizada, cómoda y profesional.')),
                ('hero_tarjeta_titulo', models.CharField(default='Servicio premium', max_length=60)),
                ('hero_tarjeta_texto', models.CharField(default='Atención personalizada', max_length=100)),
                ('hero_imagen_1', models.ImageField(blank=True, null=True, upload_to='index/hero/')),
                ('hero_imagen_2', models.ImageField(blank=True, null=True, upload_to='index/hero/')),
                ('hero_imagen_3', models.ImageField(blank=True, null=True, upload_to='index/hero/')),
                ('marca_titulo', models.CharField(default='Una barbería pensada para una experiencia más cómoda', max_length=150)),
                ('marca_descripcion', models.TextField(default='M&A Barber Shop nace para modernizar el servicio de barbería mediante una atención profesional y un sistema de agendamiento que evita largas esperas.')),
                ('marca_imagen', models.ImageField(blank=True, null=True, upload_to='index/marca/')),
                ('horario_semana', models.CharField(default='9:00 a.m. – 8:00 p.m.', max_length=60)),
                ('horario_sabado', models.CharField(default='9:00 a.m. – 6:00 p.m.', max_length=60)),
                ('telefono_fijo', models.CharField(default='(601) 123 4567', max_length=30)),
                ('whatsapp', models.CharField(default='+57 300 123 4567', max_length=30)),
                ('direccion', models.CharField(default='Carrera 27 #5a 09, Bogotá, Colombia', max_length=200)),
                ('mapa_embed_url', models.URLField(default='https://maps.google.com/maps?q=Carrera%2027%20%235a%2009,%20Bogota&t=&z=15&ie=UTF-8&iwloc=&output=embed', max_length=500)),
                ('cta_titulo', models.CharField(default='¿Listo para renovar tu estilo?', max_length=150)),
                ('cta_texto', models.CharField(default='Agenda tu cita y vive la experiencia M&A Barber Shop.', max_length=200)),
            ],
            options={
                'verbose_name': 'Contenido del Index',
                'verbose_name_plural': 'Contenido del Index',
            },
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
