# Generated by Django 4.2 on 2026-06-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.AutoField(db_column='idAgenda', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horainicio', models.TimeField(db_column='horaInicio')),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('idbarbero', models.AutoField(db_column='idBarbero', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'barbero',
                'managed': False,
            },
        ),
    ]
