# Generated by Django 4.2.19 on 2026-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='18:00')),
                ('intervalo_minutos', models.PositiveIntegerField(default=30)),
                ('limite_citas_mensuales', models.PositiveIntegerField(default=3)),
            ],
            options={
                'db_table': 'configuracion_horario',
            },
        ),
        migrations.CreateModel(
            name='DiaHabilitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dia_habilitado',
            },
        ),
    ]
