# Generated by Django 4.2.19 on 2026-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_configuracionhorario_diahabilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionhorario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diahabilitado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BarberoDiaHabilitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuariofk', models.IntegerField()),
                ('fecha', models.DateField()),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'barbero_dia_habilitado',
                'unique_together': {('idusuariofk', 'fecha')},
            },
        ),
    ]
