# Generated by Django 4.2.30 on 2026-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_alter_configuracionhorario_id_alter_diahabilitado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='patron_automatico',
            field=models.CharField(choices=[('todos', 'Todos los días'), ('lv', 'Lunes a Viernes'), ('ls', 'Lunes a Sábado')], default='lv', max_length=10),
        ),
    ]
