# Generated by Django 4.2 on 2026-06-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('idagendafk', models.IntegerField(blank=True, db_column='idAgendaFk', null=True)),
                ('fecha', models.DateField()),
                ('horainicio', models.TimeField(db_column='horaInicio')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
    ]
